services:
  db:
    build:
      context: db
    restart: always
    tty: true
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: RootPassword
      MYSQL_DATABASE: people
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    networks:
      - node_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  app_node:
    build:
      context: node
    restart: always
    container_name: app_node
    tty: true
    volumes:
      - ./node/app:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      db:
        condition: service_healthy
    networks:
      - node_net

    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=RootPassword
      - MYSQL_DB=people

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app_node
    networks:
      - node_net

networks:
  node_net:
    driver: bridge
